#!/bin/bash

if [ -f /var/lib/unattended-upgrades/kept-back ]; then
    out="$(/usr/share/unattended-upgrades/update-motd-unattended-upgrades)"
    printf "\nunattended upgrades status:\n"
    printf "  $out\n"
fi
